name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - id: version
      name: Calculate Version 
      uses: craig-day/compute-tag@v10
      with:
        github_token: ${{ github.token }}
        version_scheme: semantic
    - name: Install dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.version.outputs.next_tag }}
